[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.9,<3.15"
pandas = ">=2.1.1,<4"
ruff = ">=0.12.7,<0.16"
pytest = ">=8.1.1,<10"

[pypi-dependencies]
nuremics = { path = ".", editable = true }

[tasks]
ruff-check = "ruff check"
ruff-fix = "ruff check --fix"
tests = "pytest"
tests-basetemp = "pytest --basetemp=./.pytest_tmp"
tests-cov = "pytest --cov=nuremics --cov-report=html tests/"